### ISSUE TITLE
Pull requests: continuous-integration/travis-ci/pr — The Travis CI build failed ???

### ISSUE THREAD

**Issue by zhwangart** [hexojs/site#844] opened 2018-12-18 07:19 UTC
Pull requests: continuous-integration/travis-ci/pr — The Travis CI build failed ???

提示这个是什么原因呢？该如何解决这个 pull requests ? 我只是想替换一张图片

![Screenshot](https://user-images.githubusercontent.com/15714090/50138094-4a0bf580-02d8-11e9-86ca-22a01af8cebe.png)

**Comment by YoshinoriN** [comment] 2018-12-18 09:56
Thanks a report :)
Maybe this problem caused by package dependencies. We will try to fix it.

**Comment by YoshinoriN** [comment] 2018-12-19 15:01
Fixed in #847

**Closed by YoshinoriN** 2018-12-19 15:01 UTC
